# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efff9c602bdbfd3bc6e19ca6d0b18a970d0a695347eadc616e819838773c482475a161ea32fdf7632ed9cebd0ba8f34dae872bb107df2ee00fb35ced84992afd

test:
  secret_key_base: 9cb1f5b0102a9bf48f24316c35fb0bcf6c788304225e585442afea84934849ba8aae5782c5df308822f50858ccc5caf47946d3931a283363e4102f833c8dd923

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
